onadata/apps/api/urls.py
# coding: utf-8
from django.urls import re_path
from rest_framework import routers
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.views import APIView

from onadata.apps.api.viewsets.attachment_viewset import AttachmentViewSet
from onadata.apps.api.viewsets.briefcase_api import BriefcaseApi
from onadata.apps.api.viewsets.connect_viewset import ConnectViewSet
from onadata.apps.api.viewsets.data_viewset import DataViewSet
from onadata.apps.api.viewsets.metadata_viewset import MetaDataViewSet
from onadata.apps.api.viewsets.note_viewset import NoteViewSet
from onadata.apps.api.viewsets.xform_list_api import XFormListApi
from onadata.apps.api.viewsets.xform_submission_api import XFormSubmissionApi
from onadata.apps.api.viewsets.xform_viewset import XFormViewSet


class MultiLookupRouter(routers.DefaultRouter):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.lookups_routes = []
        self.lookups_routes.append(routers.Route(
            url=r'^{prefix}/{lookups}{trailing_slash}$',
            mapping={
                'get': 'retrieve',
                'put': 'update',
                'patch': 'partial_update',
                'delete': 'destroy'
            },
            name='{basename}-detail',
            detail=True,
            initkwargs={'suffix': 'Instance'}
        ))
        self.lookups_routes.append(self.make_routes('lookup'))
        self.lookups_routes.append(self.make_routes('lookups'))
        # Dynamically generated routes.
        # Generated using @action or @link decorators on methods of the viewset

        self.lookups_routes.append(routers.Route(
            url=[
                r'^{prefix}/{lookups}/{methodname}{trailing_slash}$',
                r'^{prefix}/{lookups}/{methodname}/{extra}{trailing_slash}$'],
            mapping={
                '{httpmethod}': '{methodname}',
            },
            name='{basename}-{methodnamehyphen}',
            detail=True,
            initkwargs={}
        ))

    @staticmethod
    def make_routes(template_text):
        return routers.Route(
            url=r'^{prefix}/{%s}{trailing_slash}$' % template_text,
            mapping={
                'get': 'list',
                'post': 'create'
            },
            name='{basename}-list',
            detail=False,
            initkwargs={'suffix': 'List'})

    def get_extra_lookup_regexes(self, route):
        ret = []
        base_regex = '(?P<{lookup_field}>[^/]+)'
        if 'extra_lookup_fields' in route.initkwargs:
            for lookup_field in route.initkwargs['extra_lookup_fields']:
                ret.append(base_regex.format(lookup_field=lookup_field))
        return '/'.join(ret)

    def get_lookup_regexes(self, viewset):
        ret = []
        lookup_fields = getattr(viewset, 'lookup_fields', None)
        if lookup_fields:
            for i in range(1, len(lookup_fields)):
                tmp = []
                for lookup_field in lookup_fields[:i + 1]:
                    if lookup_field == lookup_fields[i]:
                        base_regex = '(?P<{lookup_field}>[^/.]+)'
                    else:
                        base_regex = '(?P<{lookup_field}>[^/]+)'
                    tmp.append(base_regex.format(lookup_field=lookup_field))
                ret.append(tmp)
        return ret

    def get_lookup_routes(self, viewset):
        ret = [self.routes[0]]
        for route in self.lookups_routes:
            if route.mapping == {'{httpmethod}': '{methodname}'}:
                for extra_action in viewset.get_extra_actions():
                    methodname = extra_action.__name__
                    mapping = extra_action.mapping
                    detail = extra_action.detail
                    initkwargs = route.initkwargs.copy()
                    initkwargs.update(extra_action.kwargs)
                    name = self.replace_methodname(route.name, methodname)
                    if 'extra_lookup_fields' in initkwargs:
                        uri = route.url[1]
                        uri = self.replace_methodname(uri, methodname)
                        ret.append(routers.Route(
                            url=uri,
                            mapping=mapping,
                            name=f'{name}-extra',
                            initkwargs=initkwargs,
                            detail=detail
                        ))

                    uri = self.replace_methodname(route.url[0], methodname)
                    ret.append(routers.Route(
                        url=uri,
                        mapping=mapping,
                        name=name,
                        initkwargs=initkwargs,
                        detail=detail
                    ))
            else:
                # Standard route
                ret.append(route)
        return ret

    def get_routes(self, viewset):
        ret = []
        lookup_fields = getattr(viewset, 'lookup_fields', None)
        if lookup_fields:
            ret = self.get_lookup_routes(viewset)
        else:
            ret = super().get_routes(viewset)
        return ret

    def get_api_root_view(self):
        """
        Return a view to use as the API root.
        """
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)

        class OnaApi(APIView):
            """
## KoBo JSON Rest API endpoints:

### Data
* [/api/v1/data](/api/v1/data) - List, Retrieve submission data

### Forms
* [/api/v1/forms](/api/v1/forms) - List, Retrieve form information
* [/api/v1/media](/api/v1/media) - List, Retrieve media attachments
* [/api/v1/metadata](/api/v1/metadata) - List, Retrieve form metadata
* [/api/v1/submissions](/api/v1/submissions) - Submit XForms to a form

### Users and Organizations
* [/api/v1/user](/api/v1/user) - Return authenticated user profile info

## Status Codes

* **200** - Successful [`GET`, `PATCH`, `PUT`]
* **201** - Resource successfully created [`POST`]
* **204** - Resouce successfully deleted [`DELETE`]
* **403** - Permission denied to resource
* **404** - Resource was not found

## Authentication

KoBo JSON API enpoints support both Basic authentication
and API Token Authentication through the `Authorization` header.

### Basic Authentication

Example using curl:

    curl -X GET https://example.com/api/v1/ -u username:password

### Token Authentication

Example using curl:

    curl -X GET https://example.com/api/v1/ -H "Authorization: Token TOKEN_KEY"

### KoBo Tagging API

* [Filter form list by tags.](
/api/v1/forms#get-list-of-forms-with-specific-tags)
* [List Tags for a specific form.](
/api/v1/forms#get-list-of-tags-for-a-specific-form)
* [Tag Forms.](/api/v1/forms#tag-forms)
* [Delete a specific tag.](/api/v1/forms#delete-a-specific-tag)
* [List form data by tag.](
/api/v1/data#query-submitted-data-of-a-specific-form-using-tags)
* [Tag a specific submission](/api/v1/data#tag-a-submission-data-point)

## Using Oauth2 with the KoBo API

You can learn more about oauth2 [here](
http://tools.ietf.org/html/rfc6749).

### 1. Register your client application with KoBo - [register](\
/o/applications/register/)

- `name` - name of your application
- `client_type` - Client Type: select confidential
- `authorization_grant_type` - Authorization grant type: Authorization code
- `redirect_uri` - Redirect urls: redirection endpoint

Keep note of the `client_id` and the `client_secret`, it is required when
 requesting for an `access_token`.

### 2. Authorize client application.

The authorization url is of the form:

<pre class="prettyprint">
<b>GET</b> /o/authorize?client_id=XXXXXX&response_type=code&state=abc</pre>

example:

    http://localhost:8000/o/authorize?client_id=e8&response_type=code&state=xyz

Note: Providing the url to any user will prompt for a password and
request for read and write permission for the application whose `client_id` is
specified.

Where:

- `client_id` - is the client application id - ensure its urlencoded
- `response_type` - should be code
- `state` - a random state string that you client application will get when
   redirection happens

What happens:

1. a login page is presented, the username used to login determines the account
   that provides access.
2. redirection to the client application occurs, the url is of the form:

>   REDIRECT_URI/?state=abc&code=YYYYYYYYY

example redirect uri

    http://localhost:30000/?state=xyz&code=SWWk2PN6NdCwfpqiDiPRcLmvkw2uWd

- `code` - is the code to use to request for `access_token`
- `state` - same state string used during authorization request

Your client application should use the `code` to request for an access_token.

### 3. Request for access token.

You need to make a `POST` request with `grant_type`, `code`, `client_id` and
 `redirect_uri` as `POST` payload params. You should authenticate the request
 with `Basic Authentication` using your `client_id` and `client_secret` as
 `username:password` pair.

Request:

<pre class="prettyprint">
<b>POST</b>/o/token</pre>

Payload:

    grant_type=authorization_code&code=YYYYYYYYY&client_id=XXXXXX&
    redirect_uri=http://redirect/uri/path

curl example:

    curl -X POST -d "grant_type=authorization_code&
    code=PSwrMilnJESZVFfFsyEmEukNv0sGZ8&
    client_id=e8x4zzJJIyOikDqjPcsCJrmnU22QbpfHQo4HhRnv&
    redirect_uri=http://localhost:30000" "http://localhost:8000/o/token/"
    --user "e8:xo7i4LNpMj"

Response:

    {
        "access_token": "Q6dJBs9Vkf7a2lVI7NKLT8F7c6DfLD",
        "token_type": "Bearer", "expires_in": 36000,
        "refresh_token": "53yF3uz79K1fif2TPtNBUFJSFhgnpE",
        "scope": "read write groups"
    }

Where:

- `access_token` - access token - expires
- `refresh_token` - token to use to request a new `access_token` in case it has

onadata/apps/main/forms.py
# coding: utf-8
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy

from onadata.apps.main.models import UserProfile
from onadata.libs.utils.logger_tools import publish_xls_form


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        # Include only `require_auth` since others are now stored in KPI
        fields = ('require_auth',)


class MediaForm(forms.Form):
    media = forms.FileField(label=ugettext_lazy("Media upload"),
                            required=True)

    def clean_media(self):
        data_type = self.cleaned_data['media'].content_type
        if data_type not in ['image/jpeg', 'image/png', 'audio/mpeg']:
            raise forms.ValidationError('Only these media types are \
                                        allowed .png .jpg .mp3 .3gp .wav')


class QuickConverterForm(forms.Form):

    xls_file = forms.FileField(
        label=ugettext_lazy('XLS File'), required=True)

    def publish(self, user, id_string=None):
        if self.is_valid():
            cleaned_xls_file = self.cleaned_data['xls_file']

            # publish the xls
            return publish_xls_form(cleaned_xls_file, user, id_string)

kobocat-template/templates/base.html
{% load static %}
{% with legacy_learn_more_url="https://community.kobotoolbox.org/t/changes-to-legacy-interface-self-serve-migration-feature-into-the-new-interface/18108" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title>{% block title %}{{ SITE_NAME }}{% endblock %}</title>
    <meta name="description"
          content="{% block meta_description %}KoBoToolbox is a free and open source suite of tools for field data collection for use in challenging environments.{% endblock %}">
    <meta name="author" content="">
    {% if GOOGLE_SITE_VERIFICATION %}
        <meta name="google-site-verification" content="{{ GOOGLE_SITE_VERIFICATION }}"/>
    {% endif %}

    {% if csrf_token %}
        <meta name="csrf-token" content="{{ csrf_token }}">{% endif %}

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    {% block styles %}

        <link rel="icon" type="image/x-icon" href="{% static "images/favicon.ico" %}"/>
        <!-- iPhone + iPad icons -->
        <link rel="apple-touch-icon-precomposed" sizes="114x114"
              href="{% static "images/apple-touch-icon-114x114.png" %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72"
              href="{% static "images/apple-touch-icon-72x72-precomposed.png" %}">
        <link rel="apple-touch-icon-precomposed" href="{% static "img/apple-touch-icon-precomposed.png" %}">
        <link rel="apple-touch-icon" href="{% static "images/apple-touch-icon.png" %}">

        <link href="{% static "css/phaseout/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "css/screen.css" %}?v=20200829121939" rel="stylesheet">
        <link href="{% static "css/ona-screen-overrides.css" %}" rel="stylesheet">
        <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
        <!--[if lte IE 8]>
        <link href="{% static "css/font-awesome-ie7.css" %}" rel="stylesheet">
        <![endif]-->
        <link href="{% static "bootstrap/css/bootstrap-responsive.min.css" %}" rel="stylesheet">

        <link href="{% static "css/kobo-branding.css" %}" rel="stylesheet">
        <link href="{% static "css/published_forms.css" %}" rel="stylesheet">
        <link href="{% static "css/data_pages.css" %}" rel="stylesheet">
        <link href="{% static "css/vex.css" %}" rel="stylesheet">
        <link href="{% static "css/vex-theme-kobo.css" %}" rel="stylesheet">

        <link href="{% static "css/footable.css" %}" rel="stylesheet">
    {% endblock %}
    <!-- spot to insert stuff for google maps -->
    {% block additional-headers %}{% endblock %}
</head>

{% block body %}
    {% if not user.is_authenticated %}

        <body>
            <header class="header-bar">
                <div class="container__wide">
                    <span class="header-bar__top-logo pull-right"></span>
                    <a href="http://support.kobotoolbox.org/" class="header-bar__support pull-right" target="_blank"
                       title="Visit our self-help pages or ask a support question (opens in new tab)">Support</a>
                </div>
            </header>

    {% else %}

        <body class='authenticated'>
        {% include "topbar.html" %}

    {% endif %}

{% block before-content %}{% endblock %}

<div class="container-fluid container__wide main {{ request.resolver_match.url_name }}">
    {% block message %}
        {% if message or messages or message_list %}
            {% include "message.html" %}
        {% endif %}
    {% endblock %}
    {% block content %}
        {% if template %}{% include template %}{% endif %}
        {{ content|safe }}
    {% endblock %}
</div>

{% include "footer.html" %}

{% block below-content %}{% endblock %}

{% block javascript %}

    <!-- Le javascript -->
    <script type="text/javascript" src="{% url "javascript-catalog" %}"></script>
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/jquery-migrate.min.js" %}"></script>
    <script src="{% static "js/jquery.tablesorter.min.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrapx-clickover.js" %}"></script>
    <script src="{% static "bootstrap/js/bootstrapx-clickover-btns.js" %}"></script>
    <script src="{% static "js/application.js" %}?v=202003111451"></script>
    <script src="{% static "js/vex.combined.min.js" %}"></script>
    <script>vex.defaultOptions.className = 'vex-theme-kobo';</script>
    <script src="{% static "js/footable.min.js" %}"></script>
    <!--  -->
    <script src="{% static "js/kobo-branding.js" %}"></script>

{% endblock %}

{% block additional-javascript %}{% endblock %}

{% block google-analytics %}
    {% if GOOGLE_ANALYTICS_PROPERTY_ID %}
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', '{{ GOOGLE_ANALYTICS_PROPERTY_ID }}', '{{ GOOGLE_ANALYTICS_DOMAIN }}');
            ga('send', 'pageview');

        </script>
    {% endif %}
{% endblock %}

</body>
{% endblock %}
</html>

{% endwith %} {# legacy_learn_more_url #}

kobocat-template/templates/footer.html
{% load i18n %}
<!-- <footer class="footer">
  <div class="container">
	<p>
	  Powered by <a href="http://www.kobotoolbox.org">KoBoToolbox</a> | <a href="https://github.com/kobotoolbox/kobocat">Github code</a> (BSD License)
	</p>
  </div>
</footer>
 -->

kobocat-template/templates/outdated_data_view.html
{% extends 'base.html' %}
{% load static %}


{% block before-content %}
{% load i18n %}

<div class="sub-header-bar">
  <div class="container__wide">
    <a class="sub-header__back" href="{% url "show_form" xform.user.username xform.id_string %}"><i class="fa fa-chevron-left"></i> {% trans "Return to" %} {{ xform.title }}</a>
  </div>
</div>

<header class="data-page__header">
</header>

{% endblock %}

{% block content %}
{% load i18n %}

<section>
  {% include "outdated_link_guidance.html" %}
</section>
{% endblock %}

kobocat-template/templates/published_forms__list--empty.html
{% load humanize %}
{% load i18n %}

kobocat-template/templates/published_surveys.html
{% load humanize %}
{% load i18n %}

{% if all_forms or forms_shared_with %}

  {% if message and message.preview_url %}
    <div id="preview-modal" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>{{ message.published_survey.title }} - {% trans "Preview" %}</h3>
      </div>
      <div class="modal-body">
        <iframe src="{{message.preview_url}}"></iframe>
      </div>
      <div class="modal-footer"></div>
    </div>
  {% endif %}

  {% for xform_list in xforms_list %}
    {% if xform_list.id == "published_or_shared" %}
      <section id="{{ xform_list.id }}-forms" class="published_forms">
        {% if xform_list.xforms %}
          {% include 'published_forms__list.html' %}
        {% endif %}
      </section>
    {% else %}
      <!-- not displaying '{{ xform_list.id }}' form list -->
    {% endif %}
  {% endfor %}
{% endif %}

kobocat-template/templates/show_form_settings.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block additional-headers %}
{% load i18n %}
  <!-- a temporary way to hide the kobocat deprecated features -->
  <style type="text/css">
  #addserviceform { display: none !important; }
  </style>
{% endblock %}

{% block content %}
{% load i18n %}
  <!-- NEW SANDBOX HTML OUTSIDE THE CONTAINER -->
  {% if is_owner %}
  <div class="container__wide">
    <div class="single-project__settings--iframe">
      <div class="settings__general">
        <h2 class="settings__group-label">
          {% trans "Form Settings" %}
        </h2>

        <div class="settings__form-item">
          <label class="settings__form-label">Existing Form Files</label>
          <ul class="settings__files">
            {% for media in media_upload %}
              <li class="{% cycle 'odd' 'even' %}">
                <div>{{ media.data_value }}</div>
                <a href="{% url "download_media_data" content_user.username xform.id_string media.id %}" class="settings__files-download" {% trans "download" %}><i class="fa fa-download"></i></a>
                {% if can_edit %}
                <a href="{% url "download_media_data" content_user.username xform.id_string media.id %}?del=true" class="settings__files-delete" title="{% trans "remove" %}"><i class="fa fa-trash-o"></i></a>
                {% endif %}
              </li>
            {% endfor %}
          </ul>

          {% if can_edit %}
          <button class="single-project__button single-project__add-media">+ Add Document</button>

          <form action="{% url "edit_form" content_user.username xform.id_string %}" method="post" enctype="multipart/form-data" class="single-project__media-upload hidden">
              {% csrf_token %}
              <ul class="nav nav-tabs">
                  <li class="active"><a href="#media_upload" data-toggle="tab">Media Upload</a></li>
                  <li><a href="#media_url_add" data-toggle="tab">Media URL</a></li>
              </ul>
              <div class="tab-content">
                  <div class="tab-pane active" id="media_upload">
                      <input type="file" accept="{{ media_upload_types }}" multiple="" name="media" id="id_media">
                      <input type="submit" class="single-project__button" value="{% trans 'Upload' %}" />
                  </div>
                  <div class="tab-pane" id="media_url_add">
                      <label for="id_media">Media url:</label>
                      <input type="text" name="media_url" id="id_media_url">
                      <input type="submit" class="single-project__button" value="{% trans 'Save Media URL' %}" />
                  </div>
              </div>
          </form>
          {% endif %}
        </div>
      </div>  <!-- END .settings__general -->

    </div>
  </div>
  {% endif %}
  <!-- END NEW SANDBOX HTML OUTSIDE THE CONTAINER -->
{% endblock %}

{% block styles %}
{{ block.super }}
  <!-- NEW SANDBOX STYLES -->
  <link href="{% static "css/ios-switches.css" %}" rel="stylesheet">
  <link href="{% static "css/kobo-single-project.css" %}" rel="stylesheet">
  <!-- END NEW SANDBOX STYLES -->
{% endblock %}

{% block javascript %}
{{ block.super }}
<script src="{% static "js/jquery.poshytip.js" %}"></script>
  {% if user.is_authenticated %}
    <script type="text/javascript" src="{% static "js/form_actions.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.cookie.js" %}"></script>
  {% endif %}


<script type="text/javascript">

$('.dashboard__formbutton-preview').click(function previewModalActivate(){
  var prevWrap = $('#preview-vex .vex-kobo-body');
  if (prevWrap.data('iframeSrc') && prevWrap.children('iframe').length === 0) {
    $('<iframe>', {src: prevWrap.data('iframeSrc')}).appendTo(prevWrap);
  } else {
    console.error('iframeSrc not set for prevWrap');
  }

  vex.open({
    content: $('#preview-vex').clone(),
    contentClassName: 'vex-content vex-content-large',
  });

});


$(document).ready(function() {

    $('.btn').tooltip();

    // SMS documentation switcher
    $('#sms_support_api').change(function() {
      $('.sms_support_api_doc').each(function (){
        $(this).toggle(false);
      });
      var selected = $(this).val();
      $('#sms_support_api_doc_' + selected).toggle(true);
    });

    // Typeahead, fetch usernames for permission assign
    $('#autocomplete').typeahead(
        {
            source: function (query, process){
                return $.get('/typeahead_usernames/', {query: query}, function(data){
                    return process(data);
                });
            }
        }
    );
    //-- end

    var collect_mobile = $('#popupmodal');
    $(document).on("click", ".js-showqr", function () {
      vex.open({
        content: collect_mobile.clone(),
        contentClassName: 'vex-content vex-content-large',
      });
      div_target = $(this).attr('data-target');
      url = $(this).data('href');
      $.ajax({
        url: url,
        method: 'get',
        success: function(html){
          var contents = $('<div>'+html+'</div>');
          $('.js-img_holder', div_target).html(contents.find('img'));
          $('.qrcode__enter-data-url').html(contents.find('a'));

        }
      })
    });

    {% if xform.shared_data %}
      $('#data-shared-private').hide();
    {% else %}
      $('#data-shared-public').hide();
    {% endif %}
    {% if xform.shared %}
      $('#form-shared-private').hide();
    {% else %}
      $('#form-shared-public').hide();
    {% endif %}
    {% if not xform.encrypted %}
      $('#form-encrypted').hide();
      $('#data-encrypted').hide();
    {% endif %}

    // toggle fields
    {% if user.is_authenticated %}
        $.each(['form-shared', 'data-shared', 'active-form'], function(inx, el) {
            var cb = $('#' + el + ':checkbox');
            cb.change(function() {
              privacyEdit(cb.data('url'), el.split('-')[0]);
              // legacy
              $('#' + el + '-public').toggle();
              $('#' + el + '-private').toggle();
            });
        });
    {% endif %}
    });

</script>

    <!-- NEW SANDBOX JQUERY CALLS -->
    <script type="text/javascript">
    $(document).ready(function() {

      $(document).on("click", ".single-project__toggle-documents .doctoggle__caret", function () {
        $('.single-project__documents').toggleClass('hidden');
        $(this).toggleClass('active');
        $('.doctoggle__caret').toggleClass('fa-caret-right');
        $('.doctoggle__caret').toggleClass('fa-caret-down');
      });

      $(document).on("click", ".single-project__toggle-settings", function () {
        $('.single-project__settings').toggleClass('hidden');
        $(this).toggleClass('active');
        if($('.single-project__settings').is(":visible")) {
          $.cookie('settingsBoxOpen', true);
        } else {
          $.cookie('settingsBoxOpen', false);
        }
      });

      $(document).on("click", ".dashboard__button-download-data", function () {
        $('.dashboard__download__drop').toggleClass('hidden');
        $(this).toggleClass('active');
      });

      $(document).on("click", ".dashboard__formbutton-download", function () {
        $('.dashboard__form-drop').toggleClass('hidden');
        $(this).toggleClass('active');
      });

      $(document).on("click", ".single-project__add-media", function () {
        $('.single-project__media-upload').toggleClass('hidden');
        $(this).toggleClass('active');
      });

      $(document).on("focus", "input#title", function () {
        $('a#title_save').removeClass('hidden');
      });
      $(document).on("focus", "input#description", function () {
        $('a#description_save').removeClass('hidden');
      });

      $(document).on("click", ".single-project__add-bg-doc", function () {
        $('.single-project__documents input#id_doc').trigger('click');
      });

      $(document).on("change", "input#id_doc", function () {
        $(this).parents("form").submit();
      });

      var delete_form = $('#delete-form');
      $(document).on("click", ".single-project__button-delete", function () {
      vexDelete = vex.open({
        content: delete_form.clone(),
        contentClassName: 'vex-content vex-content-large',
      });
      });

      $(document).on("click", ".dashboard__formbutton-refresh", function () {
        vexRefresh = vex.open({
          content: $('#xls-update').clone(),
          contentClassName: 'vex-content'
        });
      });

      $(document).click(function(event) {
          if(!$(event.target).closest('.dashboard__submissions').length) {
            if($('.dashboard__download__drop').is(":visible")) {
              $('.dashboard__download__drop').addClass('hidden');
              $('.dashboard__button-download-data').removeClass('active');
            }
          }

          if(!$(event.target).closest('.dashboard__form-contents').length) {
            if($('.dashboard__form-drop').is(":visible")) {
              $('.dashboard__form-drop').addClass('hidden');
              $('.dashboard__formbutton-download').removeClass('active');
            }
          }

          if(!$(event.target).closest('.sub-header-bar').length) {
            if($('.single-project__settings').is(":visible")) {
              $('.single-project__settings').addClass('hidden');
              $('.single-project__toggle-settings').removeClass('active');
              $.cookie('settingsBoxOpen', false);
            }
          }
      });

      if ($.cookie('settingsBoxOpen') == 'true') {
        $('.single-project__settings').removeClass('hidden');
        $('.single-project__toggle-settings').addClass('active');
      }

      // question mark poshytip effect
      $('.poshytip').poshytip({
          className: 'tip__bottomarrow',
          showTimeout: 1,
          alignTo: 'target',
          alignX: 'right',
          alignY: 'top',
          offsetX: -60,
          offsetY: -5,
          liveEvents: true
      });

      // smaller parent poshytip
      $('.poshytip-small').poshytip({
          className: 'tip__bottomarrow multiline',
          showTimeout: 1,
          alignTo: 'target',
          alignX: 'right',
          alignY: 'top',
          offsetX: -25,
          offsetY: -5,
          liveEvents: true
      });

    });
    </script>
    <!-- END NEW SANDBOX JQUERY CALLS -->

{% endblock %}